### PR TITLE
Add preliminary GPU instance metadata example

### PR DESCRIPTION
**Pull request by javagl**
A **PRELIMINARY** state of an example that uses `EXT_mesh_gpu_instancing` and `EXT_structural_metadata`.

GpuInstanceMetadata gif

The sandcastle for accessing the data uses a private API. When there is a public API, this example can be updated.

### CODE REVIEW

**Comment by lilleyse** [comment]
This is a nice surprise!

You should be able to use [`EXT_instance_features`](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_instance_features) to avoid the private API.

If you feel like taking this further you could add another sample that has multiple feature ID sets

image

**Comment by javagl** [comment]
Yes, I also mentioned that at https://community.cesium.com/t/from-i3dm-to-ext-mesh-gpu-instancing/19731/2 (which was the reason for reviving the model that I stated back in https://github.com/CesiumGS/3d-tiles-samples/pull/40#issuecomment-1029196771 ...). I'll try to do the update soon, but will have to do some local updates/extensions (sic) to properly support  `EXT_instance_features`...

**Comment by javagl** [comment]
The sample has been finalized and added to the main README. 

Since it neither belongs to `EXT_mesh_features` nor to `EXT_structural_metadata`, but _combines_ multiple extensions, I think it makes sense to put it directly into a subdirectory of the `glTF` directory. But if desired, the layout can be adjusted.

Entry point: https://github.com/javagl/3d-tiles-samples/tree/add-gpu-instance-metadata-example/glTF#other-gltf-extensions

**Comment by lilleyse** [comment]
:+1:

**Pull request merged**
