### PR TITLE
Adds samples for 3D Tiles Next

### PR DESCRIPTION
**Pull request by sanjeetsuhag**
#### Status

🚧

#### Overview

This PR reorganizes the repository by dividing samples into 3D Tiles 1.0 and 3D Tiles Next folders.

#### Samples

- 3D Tiles 1.0
  - TilesetWithDiscreteLOD
  - TilesetWithExpiration
  - TilesetWithRequestVolume
  - TilesetWithTreeBillboards
- 3D Tiles Next
  - TilesetWithTilesetMetadata
  - TilesetWithTileMetadata
  - TilesetWithGroupMetadata
  - TilesetWithExternalSchema
  - ~~S2TilesetWithHeightSemantics~~
  - ImplicitTilesetWithTileMetadata
  - ~~ImplicitTilesetWithHeightSemantics~~

#### Sandcastles

*Set your local server to serve the root of the respository*

| [3D Tiles Next Metadata](http://localhost:8080/Apps/Sandcastle/index.html#c=tVdtb9s2EP4rhD+0MpLQ6V6AwnaCdZm3BqiXAE67D1Ew0NLZYkOTAkk58Yb89x1fJMuOnWQt8iGWLd4999wrL2dgeLWgo/sSNF+AtEz8DsxWGgwFyaYCxioH0T4nJ8TqCgapTOWSabLkcAca30q4I2cB74t/l6SdzP8+U6jIJei00x0ELZOBBFQK2tT/bCCnzMBn7SylncLast/rCZUxUShj+++P379LO42s5QIMWIPC16kk5F/3QYiFe9tH9atw/Be3Rfw6BstyZlnaOQyiShoQkKH4rJKZ5UqSpFvjEBIOo3JSUztA7J5EI739FnqRG/1qlAyuO8AH93g4fJrs6N6ClkxMsgIWr8F108D3UP1Dq6p8xahu4H8PUff1lbP/zTTPF6XgGbevTPcZM8/RvvFt11jetFZpEZn4bqYlTgxu+RJHiYaFWsIHIZIA2Wpc7NtH4izPk2C5NVPC48ffanONz2i37z4i1657BjPur/ZIA8tXl1otuAFqC5DJjgDGaZSxBWhGZ2J1pX5Vlcy5nE/KAjQkNdx04/XhOgN5pZlD7ZNj+nNNybPxDwzlhMk8Y8YKcI5eKSWmTI9BVjW46TbTrUBZsT1dJ5kGkJOSZTBa4kz+GISS9ixFHxDAI0UMisjnsqzsB+91y32XGzfbYxic3ZJnt5BfTL9ifremNHVnjQ7eEvmlMtwhBTf5jMTkRbo5zHD250kbs0vevCHPSq1rotukKCYKOS5i0Q7aB876ixBprU5j1LutNur1SCwz0nRgPKrVMCovBK6biIAw8CzBDO9KF9d5e+ptcfMT8cXMdiJ+GynnUePfjoD9b04bgJucGmyJ3XixBC3Yihq7QoWcmxJ/+f1AKgl+HQjCGnB5ke25VVfG0zBTXDBuG5zHslNlrVqsWyG0F80Edw0IfF5YckR2dQVd+flb3j+BLmDm2myn+v22eqsFSq1wMbOr89ztP03hzcFerk+Seow7DQFybguXjrUADS8H7dYyhs3BR6axO1OaJO6U4/vjAT6GEW5ADg54qxo2qW0au+Y3g3V1BDMHJyRpyR+Qt33yFh+7HGoJdn1k0nT7ptqMsLthz0K5+Rh5k/F68GN5o9xeXGxo6eFw30S+WpVAxxefJ6O/xxdfRmGeY498vBp/IirA+3iaQt3hLUJmYen25vGOx0qoDDjBcA20WCGPXGWVLxO0yiyMhC8a3LZzvowbdizSeu+mrCyxps4KLvKkBeZk2x5nghnzp+Pge4JltzlG23v8wsA8FitjIXs5NjVKVHafbNNlaed4j0hslb0C19grimO69RG4VJi0c/MsRbyHXRac2E+x03aQw3C4GYpxVELpODZYHBuP5e8KbsHXhBctNRwJvpfDDHM14f8E2R+OPYvOYWfoT0/rjvmFL0qlrVt3Ekp7FnCfwxIwvWmF0xUrwpi6FYa9tuoQa4Pw/GTHv2TEZx1PZpUQjkLaOR32UP6RqlDMxSkSd2LFu9NP4SWldNjDn7s1bdhytpD/Aw) | [3D Tiles Next Semantics](http://localhost:8080/Apps/Sandcastle/index.html#c=tVNbb9MwFP4rVp5SUTkdCGnKugooQyAxgZQyHggPjnPaGHyJfEnXof137LguHavGEw+N5ePzXezvdAmGOYGvbnvQTIC0hL8DYp0Gg0GShsO1aoEfn6NLZLWDi1rWciAaDQy2oH1VwhYtI9/NWMvrjI77pfJAJkHX2eQiogwFCR4U0XjcHigbYuCLDkp11lnbl0XBFSW8U8aW57Pzszo79FrGwYA1vvlbLRH6FT4IWbi1pYd/ED1nlNlVbPvKbPce2KazFQgiLaOmzqYRoqQBDtTD1k5Sy5RE+STxIRQP9zx5svjMaxTSixX/Vir2XvEPo2R8ikB8H5b76Qnz1fP/b/spjScN1/L7GMJB9aGS03zvYswW935+mGWDHywNQg3wmvM8Mh7F6FN81E7aNo/CRxMWlxdvk9zhvl63DJ9pKrTQuE3Vqe0b5WTL5OZGcSegHKf40CXILRNOVFQDyKonFK60VrpEMzzb33oS1ug4/NLbaCDt7rNWghnAtgOZn8hhP+aUCNAEr/lupZKdqu9AQ57omgfl6Z8gW6dJYA2WXiZLo5tx8XlURLaUGMshvNlKKd4QfQ3SJXIzGRPLptnc2B2HReJ+xUSvtA3vlmNcWPCzTCyYonH0pzdFjUnhz4tj6LxlA2Lt5Yl/OqKcGONP1o7zit1BnS3mhe9/BOWKhBt/GkBzsgtt3dniYyxijOeF355G2njHv5h/Aw) | [3D Tiles Next 1.0](http://localhost:8080/Apps/Sandcastle/index.html#c=rVRRb9MwEP4rVp5SUTmtENLUdRVs5W1oiJbxQHhwnSsxXOzgc7IVtP+OHTddy4r2sD7EJ/u+77vvnFxaYVmr4A4su2Aa7tgVkGoqftudpXkiu/2V0U4oDTZPBue5bj2LJGjwpMjm3danYnIlCD5b9Ok8KZ2rJ1mGRgosDbnJ2ehsnCc7rFMIBI48+GuuGfsTFsYc3LuJp4/5KFtGyBflyrkiacHBtSnyZBihRhMgSA9fN1o6ZTRLB70OYzG51Uh7a6+8dvY/8Zt5trXFf5DRseug9RDCw/B5n+/va2VF8HJ6m4/aL3X5CX41QO7WYFPB6Y0eyL/U69ICXCrElRG2oNObPdR/zu237vvdlTws01jcWujGgtdWVcqpFohbqEwL7xDTKLk3AX4AnsBFUaSx8t5wxvB63pfbNevrTsKy9ToIMZYJT9+RBVFsPlpTKQLuStDpkZvbjrUUFVjB17hZmkvT6ELp74u6BAtpL7c6OB4+Xn3RxI90wkb8TW+pc9MFf5ULoQspyCGERpfG4ErYD6CbXpwG58kwmZLbIMx63beqqo11odGU88xBVaNwQNmqkT+9IUnUv65ptk+dFqplqrg48ldjEgWRz6wbxIX67YdhNs08/gkVjQjd3rRgUWwCrBzPruMh53ya+e1xpov9/aP8Fw) |
| - | - | - |
| image | image | image |

### CODE REVIEW

**Comment by javagl** [comment]
An attempt to load the `ImplicitTilesetWithTileMetadata` locally gave the the following output for me:

```
Tile de.javagl.j3dtiles.impl.Tile@ff5b51f
Here we go: de.javagl.j3dtiles.impl.ext.implicit_tiling.TileImplicitTiling@370736d9
maximumLevel 1
subtreeLevels 2
subtrees/{level}.{x}.{y}.subtree
Attempting to resolve subtree at global coords (level=0, (0,0))
Root Uri: subtrees/0.0.0.subtree
{
  "buffers" : [ {
    "byteLength" : 32
  } ],
  "bufferViews" : [ {
    "buffer" : 0,
    "byteOffset" : 0,
    "byteLength" : 1
  }, {
    "buffer" : 0,
    "byteOffset" : 8,
    "byteLength" : 5
  }, {
    "buffer" : 0,
    "byteOffset" : 16,
    "byteLength" : 12
  } ],
  "tileAvailability" : {
    "bufferView" : 0,
    "availableCount" : 4
  },
  "contentAvailability" : {
    "constant" : 1
  },
  "childSubtreeAvailability" : {
    "constant" : 0
  },
  "extensions" : {
    "3DTILES_metadata" : {
      "class" : "tile",
      "properties" : {
        "quadrant" : {
          "bufferView" : 1
        },
        "color" : {
          "bufferView" : 2
        }
      }
    }
  }
}
Full binary data: [27, 0, 0, 0, 0, 0, 0, 0, 4, 0, 2, 3, 0, 0, 0, 0, -1, -1, -1, -1, 0, 0, 0, -1, 0, 0, 0, -1, 0, 0, 0, 0]
String of REVERSED binary bytes for tileAvailability-subtrees/0.0.0.subtree:
  11011000
Exception in thread "main" java.lang.IllegalArgumentException: The byte length is 3 for a bit length of 21, but only 1 bytes are given
```

Specifically, the `tileAvailability` from the JSON part of the `subtree` file refers to the `bufferView: 0` with `byteLength 1`, although it should have at least 3 bytes. This seems to be the same problem as in https://github.com/CesiumGS/3d-tiles/issues/512 

This might well be a bug in my implementation, but ... the numbers look wrong to me ...

**Comment by ptrgags** [comment]
@javagl this example doesn't need 21 bits, only 5.

`subtreeLevels: 2` means 2 distinct levels per subtree, so you have a root node and 4 children nodes. That's 5 nodes, and at 1 bit per node, it fits in a byte.

if `subtreeLevels = 3`, then yes, we'd need 3 bytes.

Is the spec wording clear enough for this?

**Comment by lilleyse** [comment]
We can definitely take this further in the coming weeks, but it's a decent start to get some small sample data out there

**Comment by javagl** [comment]
@ptrgags Sorry, this was indeed an error on my side. I had some mixups resulting from `maximumLevel` being *inclusive* (thus, the *number* of levels being `maximumLevel+1`), and `subtreeLevels` indicating the actual *number* of levels (meaning that the maximum level in a subtree then is `subtreeLevels-1`). There's probably a reason why this is not `maximumSubtreeLevel` (instead of `subtreeLevels`) or `numberOfLevels` (instead of `maximumLevel`). On the one hand, these are the usual "off-by-one" errors, and maybe I'm just too used to "maximum" being _exclusive_, but looking at the spec and the [bitstream lengths](https://github.com/CesiumGS/3d-tiles/tree/main/extensions/3DTILES_implicit_tiling/#availability-bitstream-lengths) and the `levelOffset`, it certainly makes sense that `bistreamLength(x)==levelOffset(x)`, and I'm not sure why I added some `+1` there at some point...

**Pull request merged**
